In [8]:
import json

f = open("/Users/andrewastakhov/dumps/pl.json", "r")
points = json.load(f)['pts']

In [9]:
from scipy.linalg import svd
import numpy as np
A = np.asarray(points)

/var/folders/ck/jb6rmtxx78j862ljh049mjtw0000gn/T/ipykernel_1817/2552534424.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  A = np.asarray(points)


Пример с одной матрицей

In [10]:
a = np.asarray(A[0])

In [11]:
U, s, Vh=svd(a)

Получить Sigma из s Хуй знает зачем сайпи говорят что это полезно

In [12]:
sigma = np.zeros(a.shape)
for i in range(min(a.shape)):
            sigma[i, i] = s[i]

А точно, как минимум для обратной проверки, "B" должно быть равно "a"

In [15]:
B = U @ sigma @ Vh

In [18]:
a

array([[367.5282953 , 411.27996727],
       [411.27996727, 570.2315431 ],
       [570.2315431 , 439.81468985]])

In [19]:
B

array([[367.5282953 , 411.27996727],
       [411.27996727, 570.2315431 ],
       [570.2315431 , 439.81468985]])

Функция итерирующая список матриц и вычисляющая свд для каждой

In [21]:
def csvd(aa):
    svdd=[]
    for j, a_ in enumerate(aa):

        a=np.asarray(a_)
        print(f"A:\n{a}")
        U, s, Vh=svd(a)
        print("U")
        print(U)
        sigma = np.zeros(a.shape)
        print("s")
        print(s)
        print("Vh")
        print(Vh)
        for i in range(min(a.shape)):
            sigma[i, i] = s[i]
        print("Sigma")
        print(sigma)
        svdd.append((a, U.tolist(), s.tolist(), Vh, sigma))


    return svdd

In [22]:
n=csvd(A)

A:
[[367.5282953  411.27996727]
 [411.27996727 570.2315431 ]
 [570.2315431  439.81468985]]
U
[[-0.48428925 -0.12512533 -0.8659143 ]
 [-0.61181407 -0.65905685  0.43741012]
 [-0.62541783  0.74161157  0.24262071]]
s
[1138.29645279  146.37500898]
Vh
[[-0.69072503 -0.72311751]
 [ 0.72311751 -0.69072503]]
Sigma
[[1138.29645279    0.        ]
 [   0.          146.37500898]
 [   0.            0.        ]]
A:
[[439.81468985 606.41515894]
 [606.41515894 428.1395325 ]
 [428.1395325  139.62391838]]
U
[[-0.65213419  0.67449093  0.34609678]
 [-0.66082103 -0.28201777 -0.69554406]
 [-0.37153272 -0.68229609  0.62963122]]
s
[1118.05423503  254.89632419]
Vh
[[-0.75722439 -0.65315483]
 [-0.65315483  0.75722439]]
Sigma
[[1118.05423503    0.        ]
 [   0.          254.89632419]
 [   0.            0.        ]]
A:
[[139.62391838 193.96186923]]
U
[[-1.]]
s
[238.98963429]
Vh
[[-0.58422583 -0.81159114]
 [-0.81159114  0.58422583]]
Sigma
[[238.98963429   0.        ]]
A:
[[193.96186923 521.81483578]
 [521.814835